version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file: .env
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.front  # si tienes uno
    ports:
      - "3000:3000"
