name: Deploy Backend (AWS App Runner)

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Tag para la imagen (ej. latest)'
        required: true
        default: latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: us-east-1
      ECR_REPO: ahorro-api
      ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      APP_RUNNER_SERVICE_ARN: ${{ secrets.APP_RUNNER_SERVICE_ARN }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push backend image
        run: |
          IMAGE="$ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPO:${{ github.event.inputs.image_tag }}"
          docker build -t "$IMAGE" ./backend
          docker push "$IMAGE"

      - name: Trigger App Runner deployment
        run: |
          aws apprunner start-deployment --service-arn "$APP_RUNNER_SERVICE_ARN"
